name: mvcapp
recipe: lamp
config:
  webroot: .
  php: '8.4'
  database: mysql:8.0
  composer_version: '2.5.8'

services:
  database:
    type: mysql:8.0
    portforward: true
    creds:
      user: lamp
      password: lamp
      database: lamp
    config:
      mysql_extra_hosts: "database.mvcapp.internal"

  appserver:
    build_as_root:
      - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    composer_version: '2.5.8'